In [1]:
import requests
import pandas as pd
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
API_KEY = "166E1F2D-5FD5-4063-BA75-CFA20CE6798B"

## CODIGO PARA EXTRACCION DE DATA SETS DE LICITACIONES Y ORDENES DE COMPRA

In [3]:
# ---------------------------------------
# Función consulta API con reintentos
# ---------------------------------------

def consultar_api(url, max_retries=5):

    for intento in range(max_retries):

        try:
            response = requests.get(url)

            if response.status_code == 200:
                return response.json()

            else:
                espera = (intento + 1) * 5
                print(f"Error {response.status_code}. Esperando {espera}s antes de reintentar...")
                time.sleep(espera)

        except Exception as e:
            print("Error conexión:", e)
            time.sleep(5)

    return None

In [4]:
# ---------------------------------------
# Función generar fechas por mes
# ---------------------------------------

def generar_fechas_mes(year, month):

    inicio = datetime(year, month, 1)

    if month == 12:
        fin = datetime(year + 1, 1, 1) - timedelta(days=1)
    else:
        fin = datetime(year, month + 1, 1) - timedelta(days=1)

    fechas = []
    actual = inicio

    while actual <= fin:
        fechas.append(actual.strftime("%d%m%Y"))
        actual += timedelta(days=1)

    return fechas

In [ ]:
# ---------------------------------------
# Descarga LICITACIONES
# ---------------------------------------

'''licitaciones_total = []

for mes in range(1, 13):

    print("\n===========================")
    print(f"Procesando MES {mes:02d} - 2025")
    print("===========================")

    fechas = generar_fechas_mes(2025, mes)

    for i, fecha in enumerate(fechas):

        print(f"Día {i+1}/{len(fechas)} → {fecha}")

        url = f"https://api.mercadopublico.cl/servicios/v1/publico/licitaciones.json?fecha={fecha}&ticket={API_KEY}"

        data = consultar_api(url)

        if data and "Listado" in data:

            cantidad = len(data["Listado"])
            print("   registros obtenidos:", cantidad)

            licitaciones_total.extend(data["Listado"])

        else:
            print("   sin datos")

        # Espera variable para evitar bloqueo API
        espera = random.uniform(1.5, 4.0)
        time.sleep(espera)'''


print("\nTotal licitaciones descargadas:", len(licitaciones_total))

df_licitaciones = pd.DataFrame(licitaciones_total)

df_licitaciones.head()

In [ ]:
# ---------------------------------------
# Exportar
# ---------------------------------------

df_licitaciones.to_csv("licitaciones_2025.csv", index=False)
df_licitaciones.to_parquet("licitaciones_2025.parquet")

print("\nArchivo licitaciones_2025.csv generado")

In [ ]:
# ---------------------------------------
# Descarga ÓRDENES DE COMPRA
# ---------------------------------------

'''ordenes_total = []

for mes in range(1, 13):

    print("\n===========================")
    print(f"Procesando MES {mes:02d} - 2025")
    print("===========================")

    fechas = generar_fechas_mes(2025, mes)

    for i, fecha in enumerate(fechas):

        print(f"Día {i+1}/{len(fechas)} → {fecha}")

        url = f"https://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?fecha={fecha}&ticket={API_KEY}"

        data = consultar_api(url)

        if data and "Listado" in data:

            cantidad = len(data["Listado"])
            print("   registros obtenidos:", cantidad)

            ordenes_total.extend(data["Listado"])

        else:
            print("   sin datos")

        # Espera aleatoria para evitar bloqueo API
        espera = random.uniform(1.5, 4.0)
        time.sleep(espera)'''


print("\nTotal órdenes de compra descargadas:", len(ordenes_total))

df_ordenes = pd.DataFrame(ordenes_total)

df_ordenes.head()

In [ ]:
# ---------------------------------------
# Exportar resultados
# ---------------------------------------

df_ordenes.to_csv("ordenes_compra_2025.csv", index=False)
df_ordenes.to_parquet("ordenes_compra_2025.parquet")

print("\nArchivo ordenes_compra_2025.csv generado")

## ALGUNAS CONSULTAS

In [5]:
df_licitaciones=pd.read_parquet("licitaciones_dataset_completo.parquet")

In [6]:
df_licitaciones.head()

,CodigoExterno,Nombre,CodigoEstado,FechaCierre
0,564162-187-L119,(id.48430) Particulas para Depto de Física,7,2020-01-01T17:04:01.527
1,1058134-381-L119,Medicamentos Enero 2020,7,2020-01-01T15:04:01.643
2,1663-111-L119,SERVICIO DE LABORATORIO DENTAL PARA PRÓTESIS M...,7,2020-01-01T21:44:01.157
3,2713-290-L119,CLASES DIRIGIDAS,7,2020-01-01T19:29:01.22
4,1058133-15-LR19,Convenio de Suministro Farmacos Inyectables Red,8,2019-11-04T15:01:00

In [7]:
df_licitaciones.columns

Index(['CodigoExterno', 'Nombre', 'CodigoEstado', 'FechaCierre'], dtype='object')

In [8]:
df_licitaciones.shape

(826238, 4)

In [9]:
df_licitaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826238 entries, 0 to 826237
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   CodigoExterno  826238 non-null  object
 1   Nombre         826238 non-null  object
 2   CodigoEstado   826238 non-null  int64
 3   FechaCierre    826237 non-null  object
dtypes: int64(1), object(3)
memory usage: 25.2+ MB

In [10]:
df_licitaciones.isnull().sum().sort_values(ascending=False)

FechaCierre      1
CodigoExterno    0
Nombre           0
CodigoEstado     0
dtype: int64

In [12]:
df_ordenes= pd.read_parquet("ordenes_compra_dataset_completo.parquet")

In [14]:
df_ordenes.head()

,Codigo,Nombre,CodigoEstado
0,1057432-1233-SE19,ORDEN DE COMPRA DESDE 1057432-109-LP19,6
1,1058012-3776-SE19,(FAR) ESPECIAL DICIEMBRE / DICLOFENACO CM Y O...,6
2,1058012-4076-SE19,"CONTROLADOS DIC ESPECIAL/CLONAZEPAM 2,5 GTS",6
3,1499-6130-SE19,SONDA ECO/ICE,6
4,1499-6381-SE19,Servicios Octubre,6

In [16]:
df_ordenes.columns

Index(['Codigo', 'Nombre', 'CodigoEstado'], dtype='object')

In [15]:
df_ordenes.shape

(13489635, 3)

In [15]:
df_ordenes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13489635 entries, 0 to 13489634
Data columns (total 3 columns):
 #   Column        Dtype
---  ------        -----
 0   Codigo        object
 1   Nombre        object
 2   CodigoEstado  int64
dtypes: int64(1), object(2)
memory usage: 308.8+ MB

In [16]:
df_ordenes.isnull().sum().sort_values(ascending=False)

Codigo          1
Nombre          0
CodigoEstado    0
dtype: int64

In [17]:
df['tipo_orden'] = df_ordenes['Codigo'].str.extract(r'-([A-Z]{2})')

# Contamos cuántas veces aparece cada tipo y sacamos el Top 3
top_3_tipos = df['tipo_orden'].value_counts().head(3)

print("Los 3 tipos de órdenes más comunes son:")
print(top_3_tipos)

Los 3 tipos de órdenes más comunes son:
tipo_orden
SE    11316
CM     8973
MC     1148
Name: count, dtype: int64

## EXTRAYENDO DETALLES PARA ENRIQUECIMIENTO DE DATA ORDENES DE COMPRA-ITEMS

In [2]:
API_KEY = "166E1F2D-5FD5-4063-BA75-CFA20CE6798B"

# Configuracion de variables a usar
MAX_WORKERS = 10 #10 hilos en paralelo, más velocidad
BATCH_SIZE = 500 #grupo de codigos escalable
FLUSH_SIZE = 2000  # cada cuántos registros guardar
mes = "2025_12"
OUTPUT_PATH = f"ordenes_detalle_{mes}.parquet"
CONTROL_PATH = f"control_codigos_{mes}.parquet"

In [3]:
# Request
def obtener_detalle(codigo):
    url = f"https://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json?codigo={codigo}&ticket={API_KEY}"
    
    headers = {"User-Agent": "data-pipeline/1.0"} #Presentación hacia la API

    for intento in range(3): #3 intentos (0; 1 y2)
        try:
            r = requests.get(url, timeout=10, headers=headers) #llamamos a la API. Si no responde en 10 segundos, corta la conexión y pasa al siguiente intento.

            if r.status_code != 200: #Si el servidor no responde bien, no es 200 (OK)
                time.sleep(1) #espera 1 segundo, vuelve a intentar
                continue

            data = r.json() #convierte la informacion a json

            if not data or "Listado" not in data: #si no tiene el formato esperado
                return {"Codigo": codigo, "status": "error"} #devuelve esto

            listado = data["Listado"] #creamos la variable para la carpeta listado

            if not listado: #si no hay datos en el listado
                return {"Codigo": codigo, "status": "empty"} #devuelve esto

            o = listado[0] #entra al primer grupo de campos

            return {
                "Codigo": o.get("Codigo"),
                "CodigoEstado": o.get("CodigoEstado"),
                "CodigoLicitacion": o.get("CodigoLicitacion"),
                "Tipo": o.get("Tipo"),
                "Total": o.get("Total"),
                "TipoMoneda": o.get("TipoMoneda"),
                "FechaCreacion": o.get("Fechas", {}).get("FechaCreacion"),
                "CodigoOrganismo": o.get("Comprador", {}).get("CodigoOrganismo"),
                "NombreOrganismo": o.get("Comprador", {}).get("NombreOrganismo"),
                "RegionUnidad": o.get("Comprador", {}).get("RegionUnidad"),
                "NombreProveedor": o.get("Proveedor", {}).get("Nombre"),
                "status": "ok"
            }

        except Exception as e:
            if intento == 2: #si el codigo falló y se encuentra en el ultimo tercer intento (0; 1 y 2)
                return {"Codigo": codigo, "status": "error"} #devuelve esto
            time.sleep(1) #si no esta en el ultimo intento que falló, espera 1 segundo y vuelve a intentar

In [4]:
# Cargar data
df = pd.read_parquet("ordenes_compra_2025_12.parquet", columns=["Codigo", "CodigoEstado"]) #cargamos la data

#Filtramos la data
df = df[
    (df["CodigoEstado"] == 6) & #Aceptadas
    (df["Codigo"].notna()) &
    (df["Codigo"].str.extract(r'-([A-Z]{2})')[0] == "SE") #usamos regex
]

codigos = df["Codigo"].drop_duplicates().tolist() #eliminamos duplicados

print("Total códigos filtrados:", len(codigos))

Total códigos filtrados: 21414

In [5]:
# Control del progreso
if os.path.exists(CONTROL_PATH): #si el archivo de CONTROL_PATH existe en mi carpeta
    df_control_old = pd.read_parquet(CONTROL_PATH) #cargamos el archivo
    procesados = set(df_control_old["Codigo"]) #convertimos a conjunto todos los codigos extraidos
else:
    df_control_old = pd.DataFrame() #si el archivo aun no existe, creamos un dataframe vacio que usaremos luego
    procesados = set() #creamos un conjunto vacio para los codigos que luego se iran procesando

codigos_pendientes = [c for c in codigos if c not in procesados] #creamos una lista con un loop que recorre codigo por codigo de la adata de codigos sin incluir lo que ya esten procesados

print("Códigos pendientes:", len(codigos_pendientes))

Códigos pendientes: 21414

In [6]:
# Pipline
buffer_data = []
buffer_control = []

for i in range(0, len(codigos_pendientes), BATCH_SIZE):
    
    batch = codigos_pendientes[i:i+BATCH_SIZE] #avanza de 500 en 500 codigos
    print(f"Procesando batch {i} - {i+len(batch)}")

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor: #paraleliza
        futures = {executor.submit(obtener_detalle, c): c for c in batch} #creamos diccionario

        for future in as_completed(futures):
            res = future.result()

            if not res:
                continue

            # separar control vs data
            status = res.get("status", "error")

            buffer_control.append({
                "Codigo": res.get("Codigo"),
                "status": status
            })

            if status == "ok":
                buffer_data.append(res)

    
    # Guardado controlado
    if len(buffer_data) >= FLUSH_SIZE:

        df_data = pd.DataFrame(buffer_data)
        df_control = pd.DataFrame(buffer_control)

        # guardar data
        if os.path.exists(OUTPUT_PATH):
            df_old = pd.read_parquet(OUTPUT_PATH)
            df_total = pd.concat([df_old, df_data], ignore_index=True)
        else:
            df_total = df_data

        df_total = df_total.drop_duplicates(subset=["Codigo"])
        df_total.to_parquet(OUTPUT_PATH, index=False)

        # guardar control
        if not df_control_old.empty:
            df_control_total = pd.concat([df_control_old, df_control], ignore_index=True)
        else:
            df_control_total = df_control

        df_control_total = df_control_total.drop_duplicates(subset=["Codigo"])
        df_control_total.to_parquet(CONTROL_PATH, index=False)

        print(f"Guardados {len(df_data)} registros")

        # limpiar buffers
        buffer_data = []
        buffer_control = []
        df_control_old = df_control_total

    time.sleep(1)

Procesando batch 0 - 500
Procesando batch 500 - 1000
Procesando batch 1000 - 1500
Procesando batch 1500 - 2000
Procesando batch 2000 - 2500
Procesando batch 2500 - 3000
Procesando batch 3000 - 3500
Procesando batch 3500 - 4000
Procesando batch 4000 - 4500
Procesando batch 4500 - 5000
Procesando batch 5000 - 5500
Procesando batch 5500 - 6000
Procesando batch 6000 - 6500
Procesando batch 6500 - 7000
Procesando batch 7000 - 7500
Procesando batch 7500 - 8000
Procesando batch 8000 - 8500
Procesando batch 8500 - 9000
Procesando batch 9000 - 9500
Procesando batch 9500 - 10000
Procesando batch 10000 - 10500
Procesando batch 10500 - 11000
Procesando batch 11000 - 11500
Procesando batch 11500 - 12000
Procesando batch 12000 - 12500
Procesando batch 12500 - 13000
Procesando batch 13000 - 13500
Procesando batch 13500 - 14000
Procesando batch 14000 - 14500
Procesando batch 14500 - 15000
Procesando batch 15000 - 15500
Procesando batch 15500 - 16000
Procesando batch 16000 - 16500
Procesando batch 16500 - 17000
Procesando batch 17000 - 17500
Procesando batch 17500 - 18000
Procesando batch 18000 - 18500
Procesando batch 18500 - 19000
Procesando batch 19000 - 19500
Procesando batch 19500 - 20000
💾 Guardados 2022 registros
Procesando batch 20000 - 20500
Procesando batch 20500 - 21000
Procesando batch 21000 - 21414

In [7]:
# Guardado Final
if buffer_data:
    df_data = pd.DataFrame(buffer_data)

    if os.path.exists(OUTPUT_PATH):
        df_old = pd.read_parquet(OUTPUT_PATH)
        df_total = pd.concat([df_old, df_data], ignore_index=True)
    else:
        df_total = df_data

    df_total = df_total.drop_duplicates(subset=["Codigo"])
    df_total.to_parquet(OUTPUT_PATH, index=False)

if buffer_control:
    df_control = pd.DataFrame(buffer_control)

    if os.path.exists(CONTROL_PATH):
        df_old = pd.read_parquet(CONTROL_PATH)
        df_control_total = pd.concat([df_old, df_control], ignore_index=True)
    else:
        df_control_total = df_control

    df_control_total = df_control_total.drop_duplicates(subset=["Codigo"])
    df_control_total.to_parquet(CONTROL_PATH, index=False)

In [8]:
# Reporte final
df_control = pd.read_parquet(CONTROL_PATH)

print("\nResumen final:")
print(df_control.groupby("status").size())

Resumen final:
status
error       3
ok       2159
dtype: int64

In [19]:
df_total.head()

,Codigo,CodigoEstado,CodigoLicitacion,Tipo,Total,TipoMoneda,FechaCreacion,CodigoOrganismo,NombreOrganismo,RegionUnidad,NombreProveedor,status
0,1023923-3237-SE25,6,,SE,3366000.0,CLP,2025-11-11T17:36:22.12,7448,SERVICIO DE SALUD HOSPITAL DE SAN FERNANDO,Región del Libertador General Bernardo O´Higgins,juan marcelo,ok
1,1057417-41919-SE25,6,1057417-123-LP24,SE,3999917.0,CLP,2025-11-20T16:52:50.133,7375,COMPLEJO ASISTENCIAL DR.VICTOR RIOS RUIZ,Región del Biobío,PV EQUIP SA,ok
2,1057434-11831-SE25,6,1057434-16-LP24,SE,200000.0,CLP,2025-12-01T10:09:55.333,7473,SERVICIO DE SALUD CONCEPCION ARAUCO CONS,Región del Biobío,TRANSPORTES JACOB FIERRO CARTES SPA,ok
3,1057434-11834-SE25,6,1057434-6-LQ24,SE,17846757.0,CLP,2025-12-01T10:29:22.627,7473,SERVICIO DE SALUD CONCEPCION ARAUCO CONS,Región del Biobío,MARÍA TERESA MÉNDEZ GUTIÉRREZ,ok
4,1057509-45539-SE25,6,1057509-14-LE24,SE,89250.0,CLP,2025-11-27T14:48:59.697,7042,HOSPITAL CLINICO HERMINDA MARTIN,Región del Ñuble,BLUNDING S.A.,ok